apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: {{ .Values.database.clusterName }}
  namespace: {{ .Release.Namespace }}
spec:
  instances: {{ .Values.database.instances }}
  {{- if gt (int .Values.database.instances) 1 }}
  primaryUpdateStrategy: {{ .Values.database.primaryUpdateStrategy }}
  {{- end }}
  storage:
    size: {{ .Values.database.storageSize }}
    storageClass: {{ .Values.database.storageClass }}
  # The following sections define how the application will connect to the database.
  # The operator will create a secret with the database user and password.
  # The service will expose the database endpoint.
  bootstrap:
    initdb:
      database: {{ .Values.database.databaseName }}
      owner: {{ .Values.database.owner }}
      # secret:
      #   name: {{ .Values.database.secretName  }}
