apiVersion: v1
kind: Service
metadata:
  name: {{ include "geo-ip-finder.fullname" . }}
  labels:
    {{- include "geo-ip-finder.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
    - port: {{ .Values.service.metricsPort }}
      targetPort: {{ .Values.service.metricsPort }}
      protocol: TCP
      name: metrics
  selector:
    {{- include "geo-ip-finder.selectorLabels" . | nindent 4 }}
