apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: geo-ip-finder-app
  namespace: argocd

spec:
  project: default
  source:
    repoURL: https://github.com/Khodesaeed/arvan_interview_challenge.git # Replace with your Git repository URL
    targetRevision: HEAD
    path: app/helm # The path to your Helm chart within the repository
    helm:
      valueFiles:
        - values.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: geo-ip-app-system # The namespace where you want to deploy the application

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
